// Generated by CoffeeScript 1.8.0
var CSON, fs;

fs = require('fs');

CSON = require('cson-safe');

module.exports = function(codec) {
  var data, stringify;
  if (codec == null) {
    codec = CSON;
  }
  stringify = codec === CSON ? CSON.stringify : require('format-json').diffy;
  data = fs.readFileSync(process.argv.pop(), 'utf8');
  data = (function() {
    try {
      return CSON.parse(data);
    } catch (_error) {
      return JSON.parse(data);
    }
  })();
  return console.log(stringify(data, null, 2));
};
